### ISSUE TITLE
Install Fails on Ubuntu 18

### ISSUE THREAD

**Issue by stuevansuk** [MysticRyuujin/guac-install#68]
Install fails on Ubuntu 18

OK
Downloading Files...
guacamole-server-1.0.0.tar.gz                     100%[============================================================================================================>] 894.45K  2.05MB/s    in 0.4s
Downloaded guacamole-server-1.0.0.tar.gz
guacamole-1.0.0.war                               100%[============================================================================================================>]   8.85M  1.28MB/s    in 12s
Downloaded guacamole-1.0.0.war
guacamole-auth-jdbc-1.0.0.tar.gz                  100%[============================================================================================================>]  12.99M  2.71MB/s    in 5.2s
Downloaded guacamole-auth-jdbc-1.0.0.tar.gz
Downloading complete.
Building Guacamole with GCC7...
Configuring...
OK
Running Make...
Failed

**Comment by MysticRyuujin** [comment]
18.10? Not there script, it an Ubuntu / Guac issue. Nothing I can do about it

**Comment by stuevansuk** [comment]
Ok no problem, running 18.04 but will check the Guac community forums. thanks.

**Comment by MysticRyuujin** [comment]
You're running 18.04 and received that? I've had multiple people tell me it works fine on 18.04

**Comment by MysticRyuujin** [comment]
I just pushed a few updates and removed the GCC7 hack as I'm pretty sure it's no longer required. I think that might be causing an issue. Can you re-try with the new script? Also there is a log at

`LOG="/tmp/guacamole_${GUACVERSION}_build.log"`

**Comment by MysticRyuujin** [comment]
I just rebuilt my 18.04 node from scratch and re-ran the script on a fresh install. It worked find with the changes I pushed...

**Comment by stuevansuk** [comment]
Hey, thanks for the updates and the addition of logging, which is useful.  My apologies, I didn't check my build, I was running 18.10 but still doesn't work.  This isn't a problem, I'll head over to Guac Community and get some feedback.

guacenc.c: In function ‘main’:
guacenc.c:79:5: error: ‘avcodec_register_all’ is deprecated [-Werror=deprecated-declarations]
     avcodec_register_all();
     ^~~~~~~~~~~~~~~~~~~~
In file included from guacenc.c:27:
/usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:4086:6: note: declared here
 void avcodec_register_all(void);
      ^~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [Makefile:761: guacenc-guacenc.o] Error 1
make[2]: Leaving directory '/tmp/guacamole-server-1.0.0/src/guacenc'
make[1]: *** [Makefile:510: all-recursive] Error 1
make[1]: Leaving directory '/tmp/guacamole-server-1.0.0'
make: *** [Makefile:432: all] Error 2

**Comment by ingobaab** [comment]
I removed the `-Werror -Wall` in `src/guacenc/Makefile ` (guacenc_CFLAGS).
Please answer me, how to do it less dirty? :-)
